### ISSUE TITLE
Date pickers and other functions

### ISSUE THREAD

**Issue by dany2709** [recoveryrecord/SurveyAndroid#1]
Waiting for new updates of the project and for the basic component date picker

**Comment by stuartrr** [comment]
Date picker is implemented seems it hasn't been documented in this repo yet.

I think just about everything from our iOS library (SurveyNative) has been implemented now.

Here is how to use the date picker:

https://github.com/recoveryrecord/SurveyNative/blob/master/Example/SurveyNative/ExampleQuestions.json#L377

Here is where it is implemented in SurveyAndroid: 

https://github.com/recoveryrecord/SurveyAndroid/search?q=date_picker

**Comment by dany2709** [comment]
Thank you. Apparently it is not fully implemented, following the example the application stops:
```
    {
      "id": "date",
      "header": "Question 16",
      "question": "What is was the best day of the last year?",
      "question_type": "date_picker",
      "date": "current_date",
      "max_date": "current_date",
      "date_diff": {
        "year": -1
      }
    },
```

DatePickerQuestionViewHolder
https://github.com/recoveryrecord/SurveyAndroid/blob/9f7582450b5e0b79a2c7ba6f890015f21af4fdcf/surveyandroid/src/main/java/com/recoveryrecord/surveyandroid/viewholder/DatePickerQuestionViewHolder.java#L17

Error:
```
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setVisibility(int)' on a null object reference
        at com.recoveryrecord.surveyandroid.viewholder.QuestionViewHolder.resetState(QuestionViewHolder.java:44)
        at com.recoveryrecord.surveyandroid.viewholder.QuestionViewHolder.bind(QuestionViewHolder.java:34)
        at com.recoveryrecord.surveyandroid.viewholder.DatePickerQuestionViewHolder.bind(DatePickerQuestionViewHolder.java:18)
        at com.recoveryrecord.surveyandroid.SurveyQuestionAdapter.onBindViewHolder(SurveyQuestionAdapter.java:163)
```

**Comment by stuartrr** [comment]
Apologies, you are correct. It seems we only use the date_picker in a feature that never made it into our Android apps so was never fully ported from SurveyNative to SurveyAndroid.

**Comment by dany2709** [comment]
No problem. Are you planning to implement the missing functions? It is vitally important for my project date_picker, table_select, spinner and I don't have much time😥😕
